# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmcli" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "e6e92023e913733ad3286bc407eee911f2fc009cb4186efa71fa5d619d1e3f03"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "645f36bf3639612a7e470d9c08c1d0b81d26063afd444ad9bf6c3b090af72eda"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b0cd91cd52189f3ed66bbde88b3b18f129043fc0471370b9f208ef0863fd30d8"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "711fda8715868767cfbd8a2cc05e6d3807114574de6a7aba675c7d3420b77acc"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mmcli"
  desc "Console Mattermost client for automation"
  homepage "https://github.com/esivres/mmcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mmcli"]
    end
  end

  # No zap stanza required
end
