# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmcli" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "89f4771488ba589cc881df161ed1c18414d90daca480d94f7fec548dc33504d5"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a1163dfb1eeb78cc570636bed3500019a01f6eb2b7b87389006bafb5761cbcc6"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "47c0565c92776f7a6fadf9ebd1457d576b94b2f2780deeb5ee0c4b44add954e1"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c6aa4465de4c80f8c2f943b393f01dc28c8bd3c8015410a151357dd0356d6472"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mmcli"
  desc "Console Mattermost client for automation"
  homepage "https://github.com/esivres/mmcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mmcli"]
    end
  end

  # No zap stanza required
end
