# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmcli" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "268a681e005cd2932f28b0a1b501e261bf27218a099179e5aeac47a7d6b89f7f"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b502f69b2402e7e7b27aa4263ec88d7ce9bdd5df2f84eb3a165c8b470ab1e981"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5b3876093d44fad58015789128322fafddce007025d48e879198aa4bb0b47265"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "efd0c0c0b9d1002a5291cb4c47565500e29c8b36b60d7f37ee718a763ebcd8f6"
      url "https://github.com/esivres/mmcli/releases/download/v#{version}/mmcli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mmcli"
  desc "Console Mattermost client for automation"
  homepage "https://github.com/esivres/mmcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mmcli"]
    end
  end

  # No zap stanza required
end
